export const TABLE_POST = "TABLE_POST";
export const USER_LIST_GET = "USER_LIST_GET";
export const LOADINF_SHOW = "LOADINF_SHOW";

//管理员

export const MANAGER_QUERY = "MANAGER_QUERY";
export const MANAGER_USER_QUERY = "MANAGER_USER_QUERY";
export const MANAGER_ADD = "MANAGER_ADD";
export const MANAGE_BASE_APPS = "MANAGE_BASE_APPS";
export const MANAGE_DELETE = "MANAGE_DELETE";
export const MANAGE_DETAIL = "MANAGE_DETAIL";
export const DOMAIN_APPS = "DOMAIN_APPS";
//域管理

export const DOMAIN_MANAGER = "DOMAIN_MANAGER";
export const DOMAIN_ADD = "DOMAIN_ADD";
export const DOMAIN_BASIC_DEATIL = "DOMAIN_BASIC_DEATIL";
export const DOMAIN_SUPPER_APP_LIST = "DOMAIN_SUPPER_APP_LIST";
